### ISSUE TITLE
Paper citation request for this repository

### ISSUE THREAD

**Issue by Maxelweb** [brandenburg/schedcat#12]
Hello, I would like to ask if it is possible to add the `CITATION.cff` file inside this repository so as to correctly cite all the authors of this library in a paper.

As you can see from [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) and [here](https://citation-file-format.github.io/), this feature has been added recently in Github and it would very useful to give the authors the appropriate credits.

The structure of the file should be something like this, as shown in the pages linked above:

```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: https://orcid.org/0000-0003-4925-7248
title: "My Research Software"
version: 2.0.4
doi: 10.5281/zenodo.1234
date-released: 2021-08-11
```
